Update npm-grunt.yml

diff --git a/.github/workflows/npm-grunt.yml b/.github/workflows/npm-grunt.yml
--- a/.github/workflows/npm-grunt.yml
+++ b/.github/workflows/npm-grunt.yml
@@ -3,8 +3,8 @@ name: NodeJS with Grunt
 on:
   push:
     branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+  # pull_request:
+  #   branches: [ "main" ]
 
 jobs:
   build:
@@ -28,13 +28,18 @@ jobs:
     - name: Build
       run: |
         npm run build
-    - name: Build
+
+        
+    - name: Check if PM2 is installed
       run: |
-        npm run build
-    - name: Install PM2 globally
-      run: |
-        npm install -g pm2
+        if ! command -v pm2 &> /dev/null
+        then
+          echo "PM2 not found, installing..."
+          npm install -g pm2
+        else
+          echo "PM2 is already installed."
+        fi
+
     - name: Start application with PM2
-      run: |
-        pm2 start npm --name antTest -- start
+      run: pm2 start npm --name antTest -- start
       
